import React, { useState } from "react";
import { createPortal } from "react-dom";
import { 
  X, Sparkles, Download, CheckCircle2, AlertTriangle, 
  Flame, TrendingUp, Target, BookOpen, Layers, Award,
  ChevronDown, ChevronUp, Copy, Check, ShieldCheck, RefreshCw, FileText
} from "lucide-react";
import { PYQ8020AnalysisReport, PYQRepeatTopic } from "../types";
import { MathRenderer } from "./MathRenderer";

interface PYQ8020ReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  report: PYQ8020AnalysisReport | null;
  isLoading: boolean;
  onRefreshOrReanalyze?: () => void;
  studentName?: string;
  addToast?: (msg: string, type: "success" | "error" | "info") => void;
}

export const PYQ8020ReportModal: React.FC<PYQ8020ReportModalProps> = ({
  isOpen,
  onClose,
  report,
  isLoading,
  onRefreshOrReanalyze,
  studentName = "Student",
  addToast
}) => {
  const [activeFilter, setActiveFilter] = useState<"all" | "guaranteed" | "high" | "moderate">("all");
  const [expandedTopicId, setExpandedTopicId] = useState<string | null>(null);
  const [masteredTopicIds, setMasteredTopicIds] = useState<Set<string>>(new Set());
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const toggleMastered = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    setMasteredTopicIds(prev => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
        if (addToast) addToast("Topic marked as Mastered! Keep up the momentum 🚀", "success");
      }
      return next;
    });
  };

  const toggleExpand = (id: string) => {
    setExpandedTopicId(prev => (prev === id ? null : id));
  };

  const handlePrint = () => {
    window.print();
  };

  const handleCopySummary = () => {
    if (!report) return;
    const allTopics = [
      ...(report.guaranteedTopics || []),
      ...(report.highYieldTopics || []),
      ...(report.moderateYieldTopics || [])
    ];
    const text = `🎯 10-YEAR PYQ 80/20 GUARANTEED REPEAT TOPICS REPORT\n` +
      `Subject: ${report.subject} (${report.grade} - ${report.board})\n` +
      `Analysis Span: ${report.yearsSpan} (10 Years Board Papers)\n` +
      `Estimated Paper Coverage: ${report.estimatedScoreCoveragePercentage}%\n\n` +
      `🔥 TOP REPEAT TOPICS:\n` +
      allTopics.map((t, i) => `${i + 1}. [${t.recurrenceFrequency}] ${t.topicName} (${t.chapterName}) - ${t.marksWeightage}`).join("\n") +
      `\n\nGenerated by Cherry AI Classroom Exam Intelligence.`;

    navigator.clipboard.writeText(text);
    setCopied(true);
    if (addToast) addToast("80/20 Report Summary copied to clipboard!", "success");
    setTimeout(() => setCopied(false), 2000);
  };

  const allTopics: PYQRepeatTopic[] = report ? [
    ...(report.guaranteedTopics || []),
    ...(report.highYieldTopics || []),
    ...(report.moderateYieldTopics || [])
  ] : [];

  const filteredTopics = allTopics.filter(t => {
    if (activeFilter === "all") return true;
    return t.priorityTier === activeFilter;
  });

  const guaranteedCount = report?.guaranteedTopics?.length || 0;
  const highCount = report?.highYieldTopics?.length || 0;
  const moderateCount = report?.moderateYieldTopics?.length || 0;
  const masteredCount = allTopics.filter(t => masteredTopicIds.has(t.id)).length;
  const progressPercent = allTopics.length > 0 ? Math.round((masteredCount / allTopics.length) * 100) : 0;

  const modalContent = (
    <div className="fixed inset-0 z-[9999] flex items-center justify-center p-2 sm:p-4 md:p-6 bg-black/75 backdrop-blur-md animate-fade-in overflow-y-auto">
      <div className="relative w-full max-w-5xl bg-[#0f172a] text-slate-100 rounded-2xl md:rounded-3xl border border-slate-700/80 shadow-2xl overflow-hidden flex flex-col max-h-[92vh] my-auto">
        
        {/* Top Header Bar */}
        <div className="flex items-center justify-between px-5 sm:px-8 py-4 border-b border-slate-800 bg-slate-900/90 sticky top-0 z-20 backdrop-blur-md">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-amber-500 to-emerald-400 p-0.5 flex items-center justify-center shadow-lg shadow-amber-500/20">
              <div className="w-full h-full bg-slate-900 rounded-[10px] flex items-center justify-center">
                <Target className="w-5 h-5 text-amber-400" />
              </div>
            </div>
            <div>
              <div className="flex items-center gap-2 flex-wrap">
                <span className="text-xs font-bold tracking-wider uppercase px-2 py-0.5 rounded-full bg-amber-500/20 text-amber-300 border border-amber-500/30">
                  80/20 Pareto Rule
                </span>
                <span className="text-xs font-semibold px-2 py-0.5 rounded-full bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
                  10-Yr PYQ Radar
                </span>
                <span className="text-xs text-slate-400">
                  {report?.yearsSpan || "2016 – 2026"}
                </span>
              </div>
              <h2 className="text-lg sm:text-xl font-bold text-white tracking-tight flex items-center gap-2">
                Guaranteed Repeat Topics Report
                <span className="hidden sm:inline-block text-xs font-normal text-slate-400">
                  • {report?.grade || "Class 10th"} {report?.subject || "Mathematics"} ({report?.board || "CBSE"})
                </span>
              </h2>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopySummary}
              title="Copy Summary"
              className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white transition-all border border-slate-700"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
            </button>
            <button
              onClick={handlePrint}
              title="Download / Print PDF"
              className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold shadow-lg shadow-emerald-600/30 transition-all border border-emerald-400/40"
            >
              <Download className="w-4 h-4" />
              <span className="hidden sm:inline">Print / Save PDF</span>
            </button>
            <button
              onClick={onClose}
              className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-white transition-all border border-slate-700"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Modal Scrollable Body */}
        <div className="p-4 sm:p-6 md:p-8 overflow-y-auto space-y-6 print:p-0 print:bg-white print:text-black">
          
          {isLoading ? (
            <div className="py-20 flex flex-col items-center justify-center text-center space-y-4">
              <div className="relative w-16 h-16">
                <div className="absolute inset-0 rounded-full border-4 border-amber-400/20 border-t-amber-400 animate-spin" />
                <Target className="w-8 h-8 text-amber-400 absolute inset-0 m-auto animate-pulse" />
              </div>
              <div>
                <h3 className="text-lg font-bold text-white">Scanning 10 Years of Board PYQs...</h3>
                <p className="text-xs text-slate-400 max-w-sm mt-1">
                  Applying the 80/20 Pareto statistical model to identify high-yield recurring questions, question evolution, and examiner trap points.
                </p>
              </div>
            </div>
          ) : report ? (
            <>
              {/* Executive Overview Banner */}
              <div className="p-4 sm:p-5 rounded-2xl bg-gradient-to-br from-slate-800/90 via-slate-800/50 to-slate-900/90 border border-slate-700/80 relative overflow-hidden shadow-xl">
                <div className="absolute top-0 right-0 w-64 h-64 bg-amber-500/10 rounded-full blur-3xl pointer-events-none" />
                
                <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 relative z-10">
                  <div className="space-y-1.5 max-w-2xl">
                    <div className="flex items-center gap-2">
                      <span className="flex h-2 w-2 relative">
                        <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75" />
                        <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500" />
                      </span>
                      <span className="text-xs font-semibold text-emerald-400 uppercase tracking-wider">
                        Report Ready • {report.subject} ({report.grade})
                      </span>
                    </div>
                    <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
                      {report.summaryExecutiveNote}
                    </p>
                  </div>

                  {/* 3 Metric Pills */}
                  <div className="flex items-center gap-2 sm:gap-3 flex-wrap md:flex-nowrap w-full md:w-auto">
                    <div className="flex-1 md:flex-none px-3.5 py-2.5 rounded-xl bg-amber-500/15 border border-amber-500/30 text-center">
                      <div className="text-lg sm:text-xl font-extrabold text-amber-300">
                        {report.estimatedScoreCoveragePercentage}%
                      </div>
                      <div className="text-[10px] font-medium text-amber-200/80 uppercase">
                        Paper Covered
                      </div>
                    </div>

                    <div className="flex-1 md:flex-none px-3.5 py-2.5 rounded-xl bg-emerald-500/15 border border-emerald-500/30 text-center">
                      <div className="text-lg sm:text-xl font-extrabold text-emerald-300">
                        {guaranteedCount}
                      </div>
                      <div className="text-[10px] font-medium text-emerald-200/80 uppercase">
                        100% Guaranteed
                      </div>
                    </div>

                    <div className="flex-1 md:flex-none px-3.5 py-2.5 rounded-xl bg-sky-500/15 border border-sky-500/30 text-center">
                      <div className="text-lg sm:text-xl font-extrabold text-sky-300">
                        {progressPercent}%
                      </div>
                      <div className="text-[10px] font-medium text-sky-200/80 uppercase">
                        Your Mastery
                      </div>
                    </div>
                  </div>
                </div>

                {/* Progress Bar */}
                <div className="mt-4 pt-4 border-t border-slate-700/60 flex items-center justify-between gap-4">
                  <div className="flex items-center gap-2 text-xs text-slate-400">
                    <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                    <span>Mastered <strong className="text-white">{masteredCount}</strong> of <strong className="text-white">{allTopics.length}</strong> Guaranteed Topics</span>
                  </div>
                  <div className="flex-1 max-w-xs h-2 rounded-full bg-slate-700 overflow-hidden">
                    <div 
                      className="h-full bg-gradient-to-r from-emerald-500 to-teal-400 transition-all duration-500"
                      style={{ width: `${progressPercent}%` }}
                    />
                  </div>
                </div>
              </div>

              {/* Filter Tabs */}
              <div className="flex items-center justify-between gap-2 flex-wrap pb-1 border-b border-slate-800">
                <div className="flex items-center gap-1.5 p-1 bg-slate-800/80 rounded-xl border border-slate-700/60">
                  <button
                    onClick={() => setActiveFilter("all")}
                    className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all ${
                      activeFilter === "all"
                        ? "bg-slate-700 text-white shadow-sm"
                        : "text-slate-400 hover:text-slate-200"
                    }`}
                  >
                    All Topics ({allTopics.length})
                  </button>
                  <button
                    onClick={() => setActiveFilter("guaranteed")}
                    className={`flex items-center gap-1 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all ${
                      activeFilter === "guaranteed"
                        ? "bg-amber-500/20 text-amber-300 border border-amber-500/40"
                        : "text-slate-400 hover:text-amber-300"
                    }`}
                  >
                    <Flame className="w-3.5 h-3.5 text-amber-400" />
                    🔥 Guaranteed ({guaranteedCount})
                  </button>
                  <button
                    onClick={() => setActiveFilter("high")}
                    className={`flex items-center gap-1 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all ${
                      activeFilter === "high"
                        ? "bg-emerald-500/20 text-emerald-300 border border-emerald-500/40"
                        : "text-slate-400 hover:text-emerald-300"
                    }`}
                  >
                    <TrendingUp className="w-3.5 h-3.5 text-emerald-400" />
                    ⚡ High Yield ({highCount})
                  </button>
                  <button
                    onClick={() => setActiveFilter("moderate")}
                    className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all ${
                      activeFilter === "moderate"
                        ? "bg-sky-500/20 text-sky-300 border border-sky-500/40"
                        : "text-slate-400 hover:text-sky-300"
                    }`}
                  >
                    📚 Moderate ({moderateCount})
                  </button>
                </div>

                {onRefreshOrReanalyze && (
                  <button
                    onClick={onRefreshOrReanalyze}
                    className="flex items-center gap-1 text-xs text-slate-400 hover:text-white px-2.5 py-1.5 rounded-lg bg-slate-800/60 hover:bg-slate-800 transition-all border border-slate-700/50"
                  >
                    <RefreshCw className="w-3.5 h-3.5" />
                    <span>Re-Analyze</span>
                  </button>
                )}
              </div>

              {/* Topics Grid / Cards */}
              <div className="space-y-4">
                {filteredTopics.map((topic, index) => {
                  const isExpanded = expandedTopicId === topic.id;
                  const isMastered = masteredTopicIds.has(topic.id);

                  return (
                    <div
                      key={topic.id}
                      className={`rounded-2xl transition-all duration-200 border ${
                        isMastered
                          ? "bg-slate-900/60 border-emerald-500/40"
                          : topic.priorityTier === "guaranteed"
                          ? "bg-slate-900/90 border-amber-500/30 hover:border-amber-500/60"
                          : "bg-slate-900/80 border-slate-700/80 hover:border-slate-600"
                      } overflow-hidden shadow-lg`}
                    >
                      {/* Topic Card Header */}
                      <div 
                        onClick={() => toggleExpand(topic.id)}
                        className="p-4 sm:p-5 flex items-start justify-between gap-3 cursor-pointer select-none"
                      >
                        <div className="flex items-start gap-3.5 flex-1">
                          <button
                            onClick={(e) => toggleMastered(topic.id, e)}
                            title={isMastered ? "Mark as Incomplete" : "Mark as Mastered"}
                            className={`mt-0.5 w-6 h-6 rounded-full flex items-center justify-center transition-all ${
                              isMastered
                                ? "bg-emerald-500 text-slate-950 shadow-md shadow-emerald-500/30"
                                : "border-2 border-slate-600 hover:border-emerald-400 text-transparent"
                            }`}
                          >
                            <Check className="w-3.5 h-3.5 stroke-[3]" />
                          </button>

                          <div className="space-y-1.5 flex-1">
                            <div className="flex items-center gap-2 flex-wrap">
                              <span className="text-[11px] font-bold px-2 py-0.5 rounded-md bg-slate-800 text-slate-300 border border-slate-700">
                                {topic.chapterName}
                              </span>

                              {topic.priorityTier === "guaranteed" ? (
                                <span className="text-[11px] font-bold px-2 py-0.5 rounded-md bg-amber-500/20 text-amber-300 border border-amber-500/40 flex items-center gap-1">
                                  <Flame className="w-3 h-3 text-amber-400" />
                                  {topic.recurrenceFrequency}
                                </span>
                              ) : topic.priorityTier === "high" ? (
                                <span className="text-[11px] font-bold px-2 py-0.5 rounded-md bg-emerald-500/20 text-emerald-300 border border-emerald-500/40 flex items-center gap-1">
                                  <TrendingUp className="w-3 h-3 text-emerald-400" />
                                  {topic.recurrenceFrequency}
                                </span>
                              ) : (
                                <span className="text-[11px] font-bold px-2 py-0.5 rounded-md bg-sky-500/20 text-sky-300 border border-sky-500/40">
                                  {topic.recurrenceFrequency}
                                </span>
                              )}

                              <span className="text-[11px] font-medium px-2 py-0.5 rounded-md bg-purple-500/20 text-purple-300 border border-purple-500/30">
                                {topic.marksWeightage}
                              </span>
                            </div>

                            <h3 className={`text-base sm:text-lg font-bold tracking-tight ${isMastered ? "line-through text-slate-400" : "text-white"}`}>
                              {topic.topicName}
                            </h3>

                            {/* Year timeline pills */}
                            <div className="flex items-center gap-1.5 flex-wrap pt-1">
                              <span className="text-[10px] uppercase font-semibold text-slate-400">
                                Appeared In:
                              </span>
                              {topic.yearsAppeared.map(yr => (
                                <span 
                                  key={yr} 
                                  className="text-[10px] font-mono font-bold px-1.5 py-0.2 rounded bg-slate-800 text-slate-300 border border-slate-700/60"
                                >
                                  {yr}
                                </span>
                              ))}
                            </div>
                          </div>
                        </div>

                        <div className="flex items-center gap-2">
                          <button
                            onClick={() => toggleExpand(topic.id)}
                            className="p-1.5 rounded-lg bg-slate-800 text-slate-400 hover:text-white"
                          >
                            {isExpanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                          </button>
                        </div>
                      </div>

                      {/* Expanded In-Depth Socratic Guidance & Traps */}
                      {isExpanded && (
                        <div className="px-5 pb-5 pt-2 border-t border-slate-800/80 space-y-4 bg-slate-950/40 animate-fade-in">
                          
                          {/* Master Formula / Theorem Box */}
                          {topic.masterFormulaOrTheoremLatex && (
                            <div className="p-3.5 rounded-xl bg-slate-900 border border-slate-700/70 space-y-1">
                              <div className="text-[10px] font-bold uppercase tracking-wider text-amber-400 flex items-center gap-1.5">
                                <Sparkles className="w-3 h-3" />
                                Master Formula / Core Theorem
                              </div>
                              <div className="text-sm font-semibold text-white py-1">
                                <MathRenderer text={`$$${topic.masterFormulaOrTheoremLatex}$$`} />
                              </div>
                            </div>
                          )}

                          {/* Question Evolution Summary */}
                          <div className="p-3.5 rounded-xl bg-slate-900/90 border border-slate-800 space-y-1">
                            <div className="text-[10px] font-bold uppercase tracking-wider text-sky-400 flex items-center gap-1.5">
                              <Layers className="w-3 h-3" />
                              10-Year Question Evolution & Rotation Trend
                            </div>
                            <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
                              {topic.questionEvolutionSummary}
                            </p>
                          </div>

                          {/* Representative Board Question */}
                          <div className="p-3.5 rounded-xl bg-purple-950/20 border border-purple-800/40 space-y-1">
                            <div className="text-[10px] font-bold uppercase tracking-wider text-purple-300 flex items-center gap-1.5">
                              <BookOpen className="w-3 h-3" />
                              Representative Board PYQ
                            </div>
                            <p className="text-xs sm:text-sm text-purple-200/90 font-medium italic">
                              "{topic.samplePYQSnippet}"
                            </p>
                          </div>

                          {/* 2-Column: Danger Traps & Step-Marking Scoring Strategy */}
                          <div className="grid grid-cols-1 md:grid-cols-2 gap-3.5 pt-1">
                            {/* Danger Traps */}
                            <div className="p-3.5 rounded-xl bg-rose-950/20 border border-rose-800/40 space-y-2">
                              <div className="text-[10px] font-bold uppercase tracking-wider text-rose-400 flex items-center gap-1.5">
                                <AlertTriangle className="w-3.5 h-3.5" />
                                ⚠️ Danger Traps (Where 90% Students Lose Marks)
                              </div>
                              <ul className="space-y-1.5 text-xs text-rose-200/90">
                                {topic.dangerTraps.map((trap, i) => (
                                  <li key={i} className="flex items-start gap-1.5">
                                    <span className="text-rose-400 font-bold">•</span>
                                    <span>{trap}</span>
                                  </li>
                                ))}
                              </ul>
                            </div>

                            {/* 100/100 Step-Marking Strategy */}
                            <div className="p-3.5 rounded-xl bg-emerald-950/20 border border-emerald-800/40 space-y-2">
                              <div className="text-[10px] font-bold uppercase tracking-wider text-emerald-400 flex items-center gap-1.5">
                                <ShieldCheck className="w-3.5 h-3.5" />
                                🎯 100/100 Step-Marking Strategy
                              </div>
                              <ul className="space-y-1.5 text-xs text-emerald-200/90">
                                {topic.stepByStepApproach.map((step, i) => (
                                  <li key={i} className="flex items-start gap-1.5">
                                    <span className="text-emerald-400 font-bold">✓</span>
                                    <span>{step}</span>
                                  </li>
                                ))}
                              </ul>
                            </div>
                          </div>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>

              {/* Master Traps Avoidance Callout */}
              {report.topTrapsToAvoid && report.topTrapsToAvoid.length > 0 && (
                <div className="p-5 rounded-2xl bg-amber-950/20 border border-amber-800/40 space-y-3">
                  <div className="flex items-center gap-2">
                    <AlertTriangle className="w-5 h-5 text-amber-400" />
                    <h4 className="text-sm font-bold text-amber-300 uppercase tracking-wider">
                      Top Board Examiner Traps to Avoid in Exam Hall
                    </h4>
                  </div>
                  <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3">
                    {report.topTrapsToAvoid.map((item, idx) => (
                      <div key={idx} className="p-3 rounded-xl bg-slate-900/90 border border-slate-800 space-y-1">
                        <div className="text-[10px] font-bold text-slate-400 uppercase">
                          {item.topic}
                        </div>
                        <div className="text-xs font-semibold text-rose-300">
                          ⚠️ {item.trap}
                        </div>
                        <div className="text-xs text-emerald-300/90">
                          💡 <strong>Fix:</strong> {item.fix}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </>
          ) : (
            <div className="py-16 text-center text-slate-400">
              No report generated yet. Click re-analyze to start.
            </div>
          )}
        </div>

        {/* Footer Bar */}
        <div className="px-6 py-4 border-t border-slate-800 bg-slate-900/90 flex items-center justify-between flex-wrap gap-3">
          <div className="text-xs text-slate-400 flex items-center gap-2">
            <Award className="w-4 h-4 text-amber-400" />
            <span>Cherry AI 10-Year PYQ Engine • Phase 1 of 3 (80/20 Rule Active)</span>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-white text-xs font-semibold border border-slate-700 transition-all"
            >
              <FileText className="w-4 h-4" />
              <span>Download Printable PDF Report</span>
            </button>
            <button
              onClick={onClose}
              className="px-5 py-2 rounded-xl bg-slate-700 hover:bg-slate-600 text-white text-xs font-semibold transition-all"
            >
              Close
            </button>
          </div>
        </div>

      </div>
    </div>
  );

  return createPortal(modalContent, document.body);
};
