/**
 * Utility to sanitize SVG strings generated by LLMs to prevent XSS attacks.
 * Strips <script> tags, inline event handlers (onload, onclick, etc.), javascript: URIs,
 * and unsafe external resources before DOM rendering.
 */
export function sanitizeSvg(rawSvg: string): string {
  if (!rawSvg || typeof rawSvg !== "string") return "";

  try {
    // 1. Parse using browser DOMParser if available
    if (typeof window !== "undefined" && window.DOMParser) {
      const parser = new DOMParser();
      const doc = parser.parseFromString(rawSvg, "image/svg+xml");

      // Check for parsing error
      const parserError = doc.querySelector("parsererror");
      if (parserError) {
        return regexSanitize(rawSvg);
      }

      // 2. Remove dangerous elements
      const dangerousTags = ["script", "iframe", "object", "embed", "link", "meta", "base"];
      dangerousTags.forEach((tag) => {
        const elements = doc.querySelectorAll(tag);
        elements.forEach((el) => el.remove());
      });

      // 3. Remove inline event handlers (on*) and javascript: hrefs/srcs/styles
      const allElements = doc.querySelectorAll("*");
      allElements.forEach((el) => {
        const attrs = Array.from(el.attributes);
        attrs.forEach((attr) => {
          const name = attr.name.toLowerCase();
          const val = attr.value.toLowerCase().trim();

          // Remove on* handlers
          if (name.startsWith("on")) {
            el.removeAttribute(attr.name);
          }
          // Remove javascript: or vbscript: URIs
          if ((name === "href" || name === "xlink:href" || name === "src") && (val.startsWith("javascript:") || val.startsWith("vbscript:"))) {
            el.removeAttribute(attr.name);
          }
          // Remove style attribute if it contains javascript: or expression
          if (name === "style" && (val.includes("javascript:") || val.includes("expression("))) {
            el.removeAttribute(attr.name);
          }
        });
      });

      // Serialize sanitized SVG back to string
      const serializer = new XMLSerializer();
      return serializer.serializeToString(doc.documentElement || doc);
    }
  } catch (e) {
    console.warn("DOMParser sanitization failed, using regex fallback:", e);
  }

  return regexSanitize(rawSvg);
}

function regexSanitize(svgStr: string): string {
  return svgStr
    .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, "")
    .replace(/\son\w+\s*=\s*(['"])(.*?)\1/gi, "")
    .replace(/\son\w+\s*=\s*([^\s>]+)/gi, "")
    .replace(/(href|xlink:href|src)\s*=\s*(['"])\s*(javascript|vbscript):[^'"]*\2/gi, "")
    .replace(/style\s*=\s*(['"])[^'"]*(javascript:|expression\()[^'"]*\1/gi, "");
}
